/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-2',
  aws_user_pools_id: 'ap-northeast-2_jFx3OOXsF',
  aws_user_pools_web_client_id: '7nofa8k50d4goe4jbkkav67nl1',
};

export default awsmobile;

export const awsConfig = {
  Auth: {
    region: 'ap-northeast-2',
    userPoolId: 'ap-northeast-2_jFx3OOXsF',
    userPoolWebClientId: '7nofa8k50d4goe4jbkkav67nl1',
    oauth: {
      domain: 'auth.nia.junah.dev',
      redirectSignIn: 'https://nia-cyan.vercel.app/token',
      redirectSignOut: 'https://nia-cyan.vercel.app/logout',
      responseType: 'token',
    },
  },
};
